"""PRISMA flow report. Counts at each pipeline stage; PRISMA-trAIce-style AI/human split.

Generates a Markdown report. SVG diagram is a future enhancement.
"""

from typing import Any

from ailr.core.project import Project


def prisma_counts(project: Project) -> dict[str, Any]:
    db = project.db
    pid = project.project_id

    total_sources = db.count_sources(pid)
    ai_summary = db.screening_summary(pid, "ai")
    human_summary = db.screening_summary(pid, "human")

    ai_decided = sum(ai_summary.values())
    human_decided = sum(human_summary.values())
    ai_included = ai_summary["include"]
    ai_excluded = ai_summary["exclude"]
    ai_uncertain = ai_summary["uncertain"]
    human_included = human_summary["include"]
    human_excluded = human_summary["exclude"]
    human_uncertain = human_summary["uncertain"]

    by_db = db.stats(pid)["by_source_database"]

    sources_with_markdown = len(db.list_sources_with_markdown(pid))
    includes_with_markdown = len(db.list_includes_with_markdown(pid))

    sources_extracted = sum(
        1 for s in db.list_sources(pid) if db.has_extraction(s.id, "ai")
    )

    return {
        "project_name": project.config.project.name,
        "project_type": project.config.project.type,
        "by_source_database": by_db,
        "total_records_identified": total_sources,
        "records_after_dedup": total_sources,  # dedup happens at ingest, so total == post-dedup
        "ai_screened": ai_decided,
        "ai_included": ai_included,
        "ai_excluded": ai_excluded,
        "ai_uncertain": ai_uncertain,
        "human_screened": human_decided,
        "human_included": human_included,
        "human_excluded": human_excluded,
        "human_uncertain": human_uncertain,
        "reports_assessed_for_eligibility": sources_with_markdown,
        "reports_assessed_includes": includes_with_markdown,
        "studies_included": sources_extracted,
    }


def build_prisma_report(project: Project) -> str:
    c = prisma_counts(project)

    lines: list[str] = []
    lines.append(f"# PRISMA Flow — {c['project_name']}")
    lines.append("")
    lines.append(f"_Project type: {c['project_type']}. Auto-generated; AI and human reviewers reported separately (PRISMA-trAIce style)._")
    lines.append("")

    lines.append("## Identification")
    lines.append("")
    if c["by_source_database"]:
        lines.append("Records identified by database:")
        for d in c["by_source_database"]:
            lines.append(f"- {d['source_database']}: {d['n']}")
    lines.append("")
    lines.append(f"**Total records identified:** {c['total_records_identified']}")
    lines.append("")
    lines.append(f"**Records after deduplication:** {c['records_after_dedup']} (dedup performed at ingest by DOI + fuzzy title)")
    lines.append("")

    lines.append("## Screening (Title + Abstract)")
    lines.append("")
    lines.append(f"**AI-screened:** {c['ai_screened']}")
    lines.append(f"- include: {c['ai_included']}")
    lines.append(f"- exclude: {c['ai_excluded']}")
    lines.append(f"- uncertain: {c['ai_uncertain']}")
    lines.append("")
    lines.append(f"**Human-screened:** {c['human_screened']}")
    lines.append(f"- include: {c['human_included']}")
    lines.append(f"- exclude: {c['human_excluded']}")
    lines.append(f"- uncertain: {c['human_uncertain']}")
    lines.append("")

    lines.append("## Eligibility (Full Text)")
    lines.append("")
    lines.append(f"**Full-text reports assessed:** {c['reports_assessed_for_eligibility']}")
    lines.append(f"- of which marked include at screening: {c['reports_assessed_includes']}")
    lines.append("")

    exclusion_counts = project.db.full_text_exclusion_counts(project.project_id)
    if exclusion_counts:
        total_excluded = sum(r["n"] for r in exclusion_counts)
        lines.append(f"**Full-text reports excluded, with reasons:** {total_excluded}")
        for r in exclusion_counts:
            lines.append(f"- {r['reason']}: {r['n']}")
        lines.append("")

    lines.append("## Included")
    lines.append("")
    lines.append(f"**Studies with completed extraction:** {c['studies_included']}")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by `ailr export --format prisma`. PRISMA 2020 / PRISMA-trAIce reporting._")

    return "\n".join(lines)
